name: Node.js CI & Deployment

on:
  push:
    branches:
      - master  # Trigger only on the 'master' branch (or 'main' depending on your setup)
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # You can expand this list if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm i  # Install the dependencies using npm

    - name: Create .env file with secret
      run: |
        touch .env  # Create the .env file
        echo "${{ secrets.DATA_PIPELINE_SERVICE_ENV }}" > .env  # Set the secret environment variable

    - name: Run build (if present)
      run: npm run build --if-present  # Run the build script if it exists

    - name: Run production environment
      run: npm run prod  # Run the 'prod' script that starts PM2 with your app
